version: "2"
plugins:
  duplication:
    enabled: true
    config:
      dump_ast: true
      debug: true
checks:
  identical-code:
    config:
      threshold: 0
  similar-code:
    config:
      threshold: 0
