version: "2"
plugins:
  duplication:
    enabled: true
    config:
      dump_ast: true
      debug: true
    checks:
      similar-code:
        config:
          threshold: 0
      identical-code:
        config:
          threshold: 0
